#
# Sitrep Scraper - Scrapebot
#

name: Scrapebot
description: Bot for mining situation reports for data
runs:
  using: docker
  image: Dockerfile
inputs:
  key:
    required: true
    description: Bot encryption key
