name: Buildbot
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/buildbot
        with:
          key: ${{ secrets.KEY }}
