name: Fetchbot
on:
  repository_dispatch:
    types:
      - execute
      - execute-dry
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/fetchbot
