name: Scrapebot
on:
  issues:
    types:
      - labeled
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/scrapebot
        with:
          key: ${{ secrets.KEY }}
